@host = http://localhost:8080

### Get all contacts
# @name getContacts
GET {{host}}/contacts

@contactId= {{getContacts.response.body.$[0]._id}}

### Get contact by id
GET {{host}}/contacts/{{contactId}}


### Create contact
# @name createContact
POST {{host}}/contacts
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/00"
}

####
@createdContactId = {{createContact.response.body._id}}

### PUT contact
PUT {{host}}/contacts/{{contactId}}
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/20"
}

### DELETE contact
DELETE {{host}}/contacts/{{contactId}}

### Create with bad fields.
PUT {{host}}/contacts/{{contactId}}
Content-Type: application/json

{
    "lastName": "",
    "email": "bad@addy",
    "birthday": "12/25/1990"
}